// <auto-generated />
using System;
using CongestionTaxCalculator.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongestionTaxCalculator.Infrastructure.Migrations
{
    [DbContext(typeof(CongestionTaxDbContext))]
    [Migration("20251113190510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.ExemptVehicleTypeDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.HasIndex("VehicleTypeId", "RuleId")
                        .IsUnique();

                    b.ToTable("ExemptVehicleTypes", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.HolidayCalendarDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("HolidayCalendar", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.PassDbModel", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Moment")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("VehicleId", "Moment");

                    b.HasIndex("VehicleId");

                    b.ToTable("Passes", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.RuleDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SingleChargePeriodMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rules", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.RulePeriodDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("RulePeriods", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.VehicleDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("TypeId");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.VehicleTypeDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("VehicleTypes", (string)null);
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.ExemptVehicleTypeDbModel", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Infrastructure.DbModels.RuleDbModel", null)
                        .WithMany("ExemptVehicles")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.PassDbModel", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Infrastructure.DbModels.VehicleDbModel", null)
                        .WithMany("Passes")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.RulePeriodDbModel", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Infrastructure.DbModels.RuleDbModel", null)
                        .WithMany("Periods")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.VehicleDbModel", b =>
                {
                    b.HasOne("CongestionTaxCalculator.Infrastructure.DbModels.VehicleTypeDbModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.RuleDbModel", b =>
                {
                    b.Navigation("ExemptVehicles");

                    b.Navigation("Periods");
                });

            modelBuilder.Entity("CongestionTaxCalculator.Infrastructure.DbModels.VehicleDbModel", b =>
                {
                    b.Navigation("Passes");
                });
#pragma warning restore 612, 618
        }
    }
}
